site_name: Richard's Blog
site_description: Blog Of A Open Source Enthusiast.
site_author: Richard Schutte
copyright: Copyright &copy; 2016 - 2020 <a href="https://richardschutte.nl">Richard Schutte</a>
repo_name: 'MKblog/base'
repo_url: https://github.com/rfjschutte/MyBlog

theme:
    name: material
    logo:
        icon: cloud
    favicon: assets/favicon.ico
    language: en
    palette:
      primary: 'blue'
      accent: 'indigo'
    font:
        text: Roboto
        code: Roboto Mono
    feature:
        tabs: true

extra:
    social:
        - type: gitlab
          link: https://gitlab.richardschutte.nl/
        - type: github
          link: https://github.com/rfjschutte
        - type: home
          link: https://richardschutte.nl
        - type: twitter
          link: https://twitter.com/richardschutte8
        - type: linkedin
          link: https://nl.linkedin.com/in/rfjschutte

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_blockdiag:
      format: svg
  - markdown_include.include
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
